### ISSUE TITLE
Removing source addresses, destination addresses, services does not trigger a change

### ISSUE THREAD

**Issue by jasonyates-thg** [pulumiverse/pulumi-fortios#10]
Using Pulumi Python, I am able to add additional entries to source addresses, destination addresses and services - this correctly detects a change and updates the Fortigate firewall policy. 

```
Updating (dev):
     Type                            Name                            Status              Info
     pulumi:pulumi:Stack             pulumi-fortigate-example-dev                        20 messages
 ~   ├─ fortios:firewall:Policy      networkmonitoring example  updated (0.52s)     [diff: ~dstaddrs]
```
However removing an element does not trigger a change.

Additionaly if I remove an element and add a new element, this does correct trigger a change.

E.g.

```
  services: 
    - SSH
    - HTTPS
```

Add a service - triggers a change 

```
  services: 
    - SSH
    - HTTPS
    - HTTP
```

Remove a service - no change triggered

```
  services: 
    - SSH
    - HTTPS
```

Removing a service and adding a new one - change triggered and rule updated correctly

```
  services: 
    - SSH
    - HTTPS
    - FTP
```

**Comment by tmeckel** [comment]
@jasonyates-thg Sounds to me like either a bug inside the Terraform provider, which is the base for the Pulumi provider. Or it's a bug in the Pulumi Terraform Bridge. I can create a new version based on the current version of Pulumi Terraform Bridge.

**Comment by tmeckel** [comment]
@jasonyates-thg have you tried the new release? If yes, any difference in the behavior of the provider?
